// <auto-generated />
using Laraue.Apps.LearnLanguage.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Laraue.Apps.LearnLanguage.DataAccess.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20261008014243_AddGlobalUserId")]
    partial class AddGlobalUserId
    {
        // Deliberately no target model. The generated one embeds the whole seed dictionary (~16 MB of
        // code) and EF builds it in memory when the migration is applied, which doesn't fit the
        // production container's memory limit. The migration's operations don't need it. The model
        // snapshot is still complete, so "migrations add" keeps working.
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
